version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: node:20
    working_dir: /app
    env_file:
      - ../dicri-backend/.env
    command: sh -c "npm install && npm run dev"
    volumes:
      - ../dicri-backend:/app
    depends_on:
      - sqlserver
      - minio
      - clamav
      - redis
    ports:
      - "3000:3000"

  web:
    image: node:20
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ../dicri-frontend:/app
    depends_on:
      - api
    ports:
      - "5173:5173"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=dicri
      - MINIO_ROOT_PASSWORD=dicri_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: -c "/init-minio.sh"
    volumes:
      - ./init-minio.sh:/init-minio.sh:ro
    environment:
      MINIO_ACCESS_KEY: dicri
      MINIO_SECRET_KEY: dicri_secret
      MINIO_BUCKET: dicri-attachments

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  sql_data:
  minio_data:
